---@meta

-- Typed argument tables for Wali's builtin task modules.
-- Builtins are imperative verbs: they do work directly and do not expose
-- declarative `state` fields.

---@alias WaliPermissionsSymlinkPolicy
---| 'skip'
---| 'error'

---@class WaliBuiltinTouchArgs
---@field path string Target-host regular file path.
---@field parents? boolean Create missing parent directories.
---@field mode? string Octal mode string.
---@field owner? WaliOwner

---@class WaliBuiltinMkdirArgs
---@field path string Target-host directory path.
---@field parents? boolean Create missing parent directories.
---@field mode? string Octal mode string.
---@field owner? WaliOwner

---@class WaliBuiltinWriteArgs
---@field src? string Controller-side text source. Mutually exclusive with content.
---@field content? string Inline text source. Mutually exclusive with src.
---@field dest string Target-host destination file.
---@field vars? table<string, WaliJsonValue> Template variables merged over task vars.
---@field parents? boolean Create missing parent directories.
---@field replace? boolean Skip when the destination exists and this is false.
---@field mode? string Octal mode string.
---@field owner? WaliOwner

---@class WaliBuiltinLinkArgs
---@field src string Symlink target text, or target-host source directory when recursive=true.
---@field dest string Target-host symlink path or recursive destination directory.
---@field parents? boolean Create the single-link parent directory.
---@field replace? boolean Skip occupied destinations when false.
---@field recursive? boolean Mirror a source directory as directories and symlinks.
---@field skip_special? boolean Skip special entries during recursive linking.
---@field max_depth? integer Recursive traversal limit.
---@field dir_mode? string Octal mode string for created directories.
---@field dir_owner? WaliOwner

---@class WaliBuiltinCopyArgs
---@field src string Target-host source file, or source directory when recursive=true.
---@field dest string Target-host destination file or directory.
---@field parents? boolean Create missing parent directories for single-file copy.
---@field replace? boolean Skip occupied destinations when false.
---@field recursive? boolean Copy a directory tree.
---@field preserve_mode? boolean Preserve source modes where applicable.
---@field preserve_owner? boolean Preserve source owner where applicable.
---@field symlinks? WaliTreeSymlinkPolicy Recursive symlink handling.
---@field skip_special? boolean Skip special entries during recursive copy.
---@field max_depth? integer Recursive traversal limit.
---@field mode? string Octal mode string applied to created/updated entries.
---@field owner? WaliOwner Owner applied to created/updated entries.
---@field dir_mode? string Octal mode override for directories.
---@field file_mode? string Octal mode override for files.
---@field dir_owner? WaliOwner Owner override for directories.
---@field file_owner? WaliOwner Owner override for files.

---@class WaliBuiltinPushArgs
---@field src string Controller-side source file, or source directory when recursive=true.
---@field dest string Target-host destination file or directory.
---@field parents? boolean Create missing parent directories for single-file push.
---@field replace? boolean Skip occupied destinations when false.
---@field recursive? boolean Transfer a directory tree.
---@field preserve_mode? boolean Preserve source modes where applicable.
---@field symlinks? WaliTreeSymlinkPolicy Recursive symlink handling.
---@field skip_special? boolean Skip special entries during recursive push.
---@field max_depth? integer Recursive traversal limit.
---@field mode? string Octal mode string applied to created/updated entries.
---@field owner? WaliOwner Owner applied to created/updated target-host entries.
---@field dir_mode? string Octal mode override for directories.
---@field file_mode? string Octal mode override for files.
---@field dir_owner? WaliOwner Owner override for directories.
---@field file_owner? WaliOwner Owner override for files.

---@class WaliBuiltinPullArgs
---@field src string Target-host source file, or source directory when recursive=true.
---@field dest string Controller-side destination file or directory.
---@field parents? boolean Create missing parent directories for single-file pull.
---@field replace? boolean Skip occupied destinations when false.
---@field recursive? boolean Transfer a directory tree.
---@field preserve_mode? boolean Preserve source modes where applicable.
---@field symlinks? WaliTreeSymlinkPolicy Recursive symlink handling.
---@field skip_special? boolean Skip special entries during recursive pull.
---@field max_depth? integer Recursive traversal limit.
---@field mode? string Octal mode string applied to controller-side destination entries where supported.
---@field dir_mode? string Octal mode override for directories.
---@field file_mode? string Octal mode override for files.

---@class WaliBuiltinRemoveArgs
---@field path string Target-host path to remove.
---@field recursive? boolean Required for non-empty directories.

---@class WaliBuiltinPermissionsArgs
---@field path string Target-host path.
---@field follow? boolean Follow the path itself when it is a symlink.
---@field expect? WaliPermissionsExpect
---@field recursive? boolean Reconcile a directory tree.
---@field symlinks? WaliPermissionsSymlinkPolicy Recursive symlink handling.
---@field skip_special? boolean Skip special entries during recursive traversal.
---@field max_depth? integer Recursive traversal limit.
---@field mode? string Octal mode string.
---@field owner? WaliOwner
---@field dir_mode? string Octal mode override for directories.
---@field file_mode? string Octal mode override for files.
---@field dir_owner? WaliOwner Owner override for directories.
---@field file_owner? WaliOwner Owner override for files.

---@class WaliBuiltinCommandArgs
---@field program? string Mutually exclusive with script.
---@field args? string[]
---@field script? string Mutually exclusive with program.
---@field cwd? string
---@field env? table<string, string>
---@field stdin? string
---@field timeout? string Human duration such as '10s' or '2m'.
---@field pty? WaliPtyMode
---@field creates? string|string[] Skip command when all listed absolute paths already exist.
---@field removes? string|string[] Skip command when all listed absolute paths are already absent.
---@field changed? boolean Report a successful run as changed. Defaults to true.

---@alias WaliBuiltinModuleArgs
---| WaliBuiltinTouchArgs
---| WaliBuiltinMkdirArgs
---| WaliBuiltinWriteArgs
---| WaliBuiltinLinkArgs
---| WaliBuiltinCopyArgs
---| WaliBuiltinPushArgs
---| WaliBuiltinPullArgs
---| WaliBuiltinRemoveArgs
---| WaliBuiltinPermissionsArgs
---| WaliBuiltinCommandArgs

---@alias WaliBuiltinModuleName
---| 'wali.builtin.touch'
---| 'wali.builtin.mkdir'
---| 'wali.builtin.write'
---| 'wali.builtin.link'
---| 'wali.builtin.copy'
---| 'wali.builtin.push'
---| 'wali.builtin.pull'
---| 'wali.builtin.remove'
---| 'wali.builtin.permissions'
---| 'wali.builtin.command'
